export * from './Login';
export * from './ForgotPass';
export * from './SignUp';
export {default as NotesList} from './NotesList';
export {default as PhotoNote} from './PhotoNote';
export {default as VoiceNote} from './VoiceNote';
export {default as AddNote} from './AddNote';
export {default as Favourites} from './Favourites';
export {default as Theme} from './Theme';
export * from './Profile';
export * from './Settings';
